# Generated by Django 2.2 on 2019-07-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_prod_for_rent',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_image', models.FileField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('1', "Men's Clothing"), ('2', "Women's Clothing"), ('3', "Electronic's"), ('4', 'Furniture'), ('5', 'Books'), ('6', 'Others')], default='Others', max_length=50)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_prod_for_sell',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_image', models.FileField(upload_to='')),
                ('category', models.CharField(choices=[('1', "Men's Clothing"), ('2', "Women's Clothing"), ('3', "Electronic's"), ('4', 'Furniture'), ('5', 'Books'), ('6', 'Others')], default='Others', max_length=50)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('house_no', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SellFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradlee.add_prod_for_sell')),
            ],
        ),
        migrations.CreateModel(
            name='RentFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradlee.add_prod_for_rent')),
            ],
        ),
    ]
